#!/bin/sh
#
# Music Player Demon Process
#

#Give The scripts that are doing to run Names
USB_Scanner=/Project/USB_Detection.bash
Play_music=/project/playmusic.bash



start_Setup() 
{
	#Setup the Sound Card
	modprobe snd-bcm2835 	
}
start_Demon_Scripts() {

		start-stop-daemon -b --start --quiet --exec ${USB_Scanner}
}

Music_Demon_Scripts() {
		start-stop-daemon -b --start --quiet --exec ${Play_music}
}
	
#execute the Functions
start_Setup
start_Demon_Scripts
Music_Demon_Scripts
